version: '3.8'

services:
  web:
    build: .
    ports:
      - "5000:5000"
    environment:
      # In Render, you'll replace this with the DATABASE_URL they provide
      - DATABASE_URL=postgresql://postgres:password@db:5432/travel
    depends_on:
      - db

  db:
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: travel
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
